Fix gitian build qt link error (#112)
Since ae8d77574d4a1eb4cf3c361dfe298fe0d82e28b6

src/qt/bitcoin.cpp:562: undefined reference to qInitResources_bitcoin()
collect2: error: ld returned 1 exit status